version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  access:
    format: "%(asctime)s - %(levelname)s - %(client_addr)s - %(method)s %(path)s - %(status_code)s"

handlers:
  default:
    class: logging.FileHandler
    filename: app.log
    formatter: default
  access:
    class: logging.FileHandler
    filename: access.log
    formatter: access

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
  uvicorn.error:
    handlers: [default]
    level: INFO
